### ISSUE TITLE
This plugin needs a WebServiceUserProvider to be more flexible

### ISSUE THREAD

**Issue by tperrelli** [Pod-Point/laravel-passport-auth#18]
First of all, congratulations for doing this package.

But, it would be nice if there is a way to persist sessions between different systems sharing the the same user database. The things is that i have 3 systems where one of those is responsible for user accesses.

The way this package is build, code check if there is a "local"user in hasValidCredentials function at Guard class.

What about a WebServiceUserProvider to allow this?

**Comment by threesquared** [comment]
Hi @tperrelli and thanks for the feedback! Your idea sounds interesting but its not something we are actively trying to develop as it doesn't fit our specific use case. However we are willing to review any contributions if you want to submit a a pull request. Thanks!
